spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 623163
    driver-class-name: com.mysql.cj.jdbc.Driver


  session:
    store-type: redis  # 指定Spring Session的存储类型为Redis
    redis:
      flush-mode: on-save  # 设置Redis会话的刷新模式为"on-save"，即在每次会话修改后保存

  redis:
    host: localhost  # Redis服务器的主机名或IP地址，这里是本地
    port: 6379       # Redis服务器的端口，默认为6379

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: apiService


server:
  port: 8080  # 将 8080 替换为你需要的端口号




moonshot:  #kmai 密钥
  api:
    key: sk-Gh6rMCadjSUFOCDtwYvCnPxOfMNwRqm90eNNRFODAa4xF3Al






